apiVersion: v1
kind: Service
metadata:
  name: django-backend
spec:
  selector:
    app: restaurant-deployment-backend
  ports:
    - protocol: TCP
      port: 80        
      targetPort: 8000 
  type: LoadBalancer     
